### ISSUE TITLE
Register and Auth

### ISSUE THREAD

**Issue by E-Hidalgo** [E-Hidalgo/final-project-assembler#2]
- [ ]  Autentificación de Usuario Autentificación de Usuario #4
- [ ] Guardado de credenciales Guardado de credenciales #6
- [ ] Cierre de sesión de usuario Cierre de sesión de usuario #7
- [ ]Registro de Usuarios Registro de Usuarios #8
- [ ] Recuperación de password Recuperación de password #9
